#ifndef __STORAGE_LEVEL_H__
#define __STORAGE_LEVEL_H__

enum StorageLevel {
	NONE,
	DISK_ONLY,
	DISK_ONLY_2,
	MEMORY_ONLY,
	MEMORY_ONLY_2,
	MEMORY_ONLY_SER,
	MEMORY_ONLY_SER_2,
	MEMORY_AND_DISK,
	MEMORY_AND_DISK_2,
	MEMORY_AND_DISK_SER,
	MEMORY_AND_DISK_SER_2
};

char* getStorageLevel(StorageLevel level);
#endif //__STORAGE_LEVEL_HPP__
