/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class spark_api_java_jni_Native */

#ifndef _Included_spark_api_java_jni_Native
#define _Included_spark_api_java_jni_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     spark_api_java_jni_Native
 * Method:    callFlatMap
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Iterable;
 */
JNIEXPORT jobject JNICALL Java_spark_api_java_jni_Native_callFlatMap
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     spark_api_java_jni_Native
 * Method:    function2call
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_spark_api_java_jni_Native_function2call
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     spark_api_java_jni_Native
 * Method:    functionCall
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_spark_api_java_jni_Native_functionCall
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     spark_api_java_jni_Native
 * Method:    pairCall
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_spark_api_java_jni_Native_pairCall
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
